"""Generate database/seed.sql from the skill taxonomy and seed_data.py.

    python scripts/generate_seed.py [--admin-email admin@jobsense.local] [--admin-password Admin@12345]

The default admin password is for local development only - change it after first login
or create your own admin with `flask --app run create-admin`.
"""
import argparse
import json
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))
sys.path.insert(0, str(BACKEND / "scripts"))

from werkzeug.security import generate_password_hash  # noqa: E402

from app.ml.skill_extraction.taxonomy import SKILL_INDEX, SKILLS, canonical_skill  # noqa: E402
from seed_data import CAREERS, RESOURCES  # noqa: E402

OUTPUT = BACKEND.parent / "database" / "seed.sql"


def q(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def validate():
    problems = []
    for career in CAREERS:
        for skill in career["skills"]:
            if skill.lower() not in SKILL_INDEX:
                problems.append(f"Career '{career['name']}' uses unknown skill '{skill}'")
    for skill, *_ in RESOURCES:
        if canonical_skill(skill) != skill or skill.lower() not in SKILL_INDEX:
            problems.append(f"Resource skill '{skill}' is not a canonical taxonomy skill")
    if problems:
        raise SystemExit("\n".join(problems))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--admin-email", default="admin@jobsense.local")
    parser.add_argument("--admin-password", default="Admin@12345")
    args = parser.parse_args()
    validate()

    out = [
        "-- =====================================================================",
        "-- JobSense seed data (generated by backend/scripts/generate_seed.py - do not edit by hand)",
        "-- Run after schema.sql:  mysql -u <user> -p jobsense < database/seed.sql",
        "-- Contains: admin account, skill taxonomy, career paths, career skills, learning resources.",
        "-- No job listings are seeded: jobs come only from the job provider (JSearch, or clearly",
        "-- labelled mock data in development).",
        "-- =====================================================================",
        "SET NAMES utf8mb4;",
        "",
        f"-- Default admin (email: {args.admin_email} / password: {args.admin_password}).",
        "-- CHANGE THIS PASSWORD or create your own admin: flask --app run create-admin",
        "INSERT INTO users (name, email, password_hash, role) VALUES "
        f"('Administrator', {q(args.admin_email)}, {q(generate_password_hash(args.admin_password, method='scrypt'))}, 'admin');",
        "INSERT INTO user_profiles (user_id) SELECT user_id FROM users WHERE email = " + q(args.admin_email) + ";",
        "",
        "-- Skill taxonomy",
    ]
    rows = [f"({q(s['name'])}, {q(s['category'])}, {q(json.dumps(s['aliases'] + s['ambiguous']))})" for s in SKILLS]
    out.append("INSERT INTO skill_taxonomy (skill_name, category, aliases) VALUES\n  " + ",\n  ".join(rows) + ";")
    out.append("")
    out.append("-- Career paths")
    rows = [f"({q(c['name'])}, {q(c['description'])}, {q(c['interest'])})" for c in CAREERS]
    out.append("INSERT INTO career_paths (career_name, description, interest_area) VALUES\n  " + ",\n  ".join(rows) + ";")
    out.append("")
    out.append("-- Career skills (importance: 3 = core, 2 = important, 1 = nice to have)")
    for c in CAREERS:
        values = ",\n  ".join(
            f"((SELECT career_id FROM career_paths WHERE career_name = {q(c['name'])}), {q(skill)}, {imp})"
            for skill, imp in c["skills"].items())
        out.append(f"INSERT INTO career_skills (career_id, skill_name, importance) VALUES\n  {values};")
    out.append("")
    out.append("-- Learning resources (official documentation and reputable references)")
    rows = [f"({q(s)}, {q(n)}, {q(u)}, {q(d)}, {q(t)})" for s, n, u, t, d in RESOURCES]
    out.append("INSERT INTO learning_resources (skill_name, resource_name, resource_url, description, resource_type) "
               "VALUES\n  " + ",\n  ".join(rows) + ";")
    out.append("")
    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(SKILLS)} skills, {len(CAREERS)} careers, {len(RESOURCES)} resources)")


if __name__ == "__main__":
    main()
