"""Reference data for database/seed.sql (career paths, career skills, learning resources).

Importance: 3 = core, 2 = important, 1 = nice to have.
Learning resources favour official documentation and well-known reference material.
No job listings are seeded - jobs only come from the job provider.
"""

CAREERS = [
    {"name": "Frontend Developer", "interest": "Web Development",
     "description": "Builds the user-facing part of web applications: layouts, interactive components, "
                    "accessibility and performance in the browser.",
     "skills": {"HTML": 3, "CSS": 3, "JavaScript": 3, "React": 3, "TypeScript": 2, "Responsive Design": 2,
                "Git": 2, "REST APIs": 2, "Redux": 1, "Jest": 1, "Accessibility": 1, "Next.js": 1}},
    {"name": "Backend Developer", "interest": "Backend Development",
     "description": "Designs and implements server-side logic, APIs, databases and integrations that power "
                    "applications.",
     "skills": {"REST APIs": 3, "SQL": 3, "Node.js": 2, "Python": 2, "Java": 2, "MySQL": 2, "Git": 2,
                "Docker": 2, "Microservices": 1, "PostgreSQL": 1, "Linux": 1, "Unit Testing": 1,
                "System Design": 1}},
    {"name": "Full Stack Developer", "interest": "Web Development",
     "description": "Works across the whole web stack - from database and API to the user interface - and "
                    "delivers features end to end.",
     "skills": {"JavaScript": 3, "React": 3, "Node.js": 3, "REST APIs": 3, "HTML": 2, "CSS": 2, "SQL": 2,
                "Git": 2, "TypeScript": 1, "MongoDB": 1, "Docker": 1, "AWS": 1}},
    {"name": "Python Developer", "interest": "Backend Development",
     "description": "Builds applications, services and automation in Python, commonly with web frameworks such "
                    "as Flask or Django.",
     "skills": {"Python": 3, "REST APIs": 3, "Flask": 2, "Django": 2, "SQL": 2, "OOP": 2, "Git": 2,
                "pytest": 1, "Linux": 1, "Docker": 1}},
    {"name": "Java Developer", "interest": "Backend Development",
     "description": "Develops robust enterprise and backend applications on the Java platform, typically with "
                    "Spring Boot.",
     "skills": {"Java": 3, "Spring Boot": 3, "OOP": 2, "SQL": 2, "Hibernate": 2, "REST APIs": 2, "Git": 2,
                "Microservices": 1, "JUnit": 1, "Data Structures": 1}},
    {"name": "Data Analyst", "interest": "Data",
     "description": "Collects, cleans and analyses data to answer business questions and communicates the "
                    "findings through reports and dashboards.",
     "skills": {"SQL": 3, "Excel": 3, "Data Analysis": 3, "Power BI": 2, "Tableau": 2, "Python": 2,
                "Statistics": 2, "Data Visualization": 2, "Pandas": 1}},
    {"name": "Data Scientist", "interest": "AI/ML",
     "description": "Applies statistics and machine learning to data to build predictive models and "
                    "generate insights.",
     "skills": {"Python": 3, "Machine Learning": 3, "Statistics": 3, "Pandas": 2, "NumPy": 2, "scikit-learn": 2,
                "SQL": 2, "Data Visualization": 1, "Deep Learning": 1, "Jupyter": 1, "Feature Engineering": 1}},
    {"name": "Machine Learning Engineer", "interest": "AI/ML",
     "description": "Designs, trains, deploys and maintains machine learning models in production systems.",
     "skills": {"Python": 3, "Machine Learning": 3, "Deep Learning": 3, "TensorFlow": 2, "PyTorch": 2,
                "scikit-learn": 2, "MLOps": 2, "Docker": 1, "SQL": 1, "Git": 1, "AWS": 1}},
    {"name": "NLP Engineer", "interest": "AI/ML",
     "description": "Builds systems that process and understand human language, such as text classification, "
                    "information extraction and search.",
     "skills": {"Python": 3, "NLP": 3, "Machine Learning": 3, "spaCy": 2, "Hugging Face": 2, "Deep Learning": 2,
                "NLTK": 1, "PyTorch": 1, "REST APIs": 1}},
    {"name": "DevOps Engineer", "interest": "DevOps",
     "description": "Automates building, testing, deployment and operation of software, bridging development "
                    "and infrastructure.",
     "skills": {"Linux": 3, "Docker": 3, "CI/CD": 3, "Kubernetes": 2, "Git": 2, "Terraform": 2, "Jenkins": 2,
                "AWS": 2, "Bash": 2, "Ansible": 1, "Monitoring": 1}},
    {"name": "Cloud Engineer", "interest": "Cloud",
     "description": "Designs, builds and operates secure, scalable infrastructure on cloud platforms.",
     "skills": {"AWS": 3, "Linux": 3, "Azure": 2, "Networking": 2, "Terraform": 2, "Docker": 2,
                "Kubernetes": 2, "IAM": 2, "Google Cloud": 1, "Python": 1}},
    {"name": "QA Engineer", "interest": "Testing",
     "description": "Ensures software quality by planning and executing tests, reporting defects and "
                    "improving test processes.",
     "skills": {"Software Testing": 3, "API Testing": 2, "SQL": 2, "Jira": 2, "Agile": 2, "Postman": 2,
                "Test Automation": 1, "Selenium": 1}},
    {"name": "Automation Test Engineer", "interest": "Testing",
     "description": "Builds and maintains automated test suites and integrates them into delivery pipelines.",
     "skills": {"Test Automation": 3, "Selenium": 3, "Java": 2, "Python": 2, "API Testing": 2, "Git": 2,
                "Cypress": 1, "Playwright": 1, "CI/CD": 1, "Cucumber": 1, "JUnit": 1}},
    {"name": "Cybersecurity Analyst", "interest": "Cybersecurity",
     "description": "Protects systems and data by monitoring for threats, investigating incidents and "
                    "reducing vulnerabilities.",
     "skills": {"Cybersecurity": 3, "Networking": 3, "Linux": 2, "SIEM": 2, "Incident Response": 2,
                "Vulnerability Assessment": 2, "Firewalls": 2, "Wireshark": 1, "Penetration Testing": 1,
                "Cryptography": 1, "IAM": 1}},
    {"name": "Mobile App Developer", "interest": "Mobile Development",
     "description": "Builds native or cross-platform applications for Android and iOS devices.",
     "skills": {"Android": 3, "Kotlin": 3, "Java": 2, "REST APIs": 2, "Git": 2, "Firebase": 1, "Flutter": 1,
                "React Native": 1, "iOS": 1}},
]

D, G, T, R, C = "documentation", "guide", "tutorial", "reference", "course"

RESOURCES = [
    # skill, name, url, type, description
    ("Python", "Python Documentation", "https://docs.python.org/3/", D, "Official Python language and standard library documentation."),
    ("Python", "The Python Tutorial", "https://docs.python.org/3/tutorial/", T, "Official introductory tutorial to Python."),
    ("Java", "Dev.java - Learn Java", "https://dev.java/learn/", T, "Official Java learning path from Oracle."),
    ("Java", "Java SE Documentation", "https://docs.oracle.com/en/java/", D, "Official Java platform documentation."),
    ("JavaScript", "MDN JavaScript Documentation", "https://developer.mozilla.org/en-US/docs/Web/JavaScript", D, "Complete JavaScript reference and guides."),
    ("JavaScript", "MDN JavaScript Guide", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", G, "Step-by-step guide to JavaScript fundamentals."),
    ("TypeScript", "TypeScript Documentation", "https://www.typescriptlang.org/docs/", D, "Official TypeScript documentation."),
    ("TypeScript", "The TypeScript Handbook", "https://www.typescriptlang.org/docs/handbook/intro.html", G, "Official handbook covering the type system."),
    ("HTML", "MDN HTML Documentation", "https://developer.mozilla.org/en-US/docs/Web/HTML", D, "HTML elements, attributes and guides."),
    ("CSS", "MDN CSS Documentation", "https://developer.mozilla.org/en-US/docs/Web/CSS", D, "CSS properties, layout and guides."),
    ("React", "React Documentation - Learn", "https://react.dev/learn", D, "Official React docs: components, state and hooks."),
    ("React", "React API Reference", "https://react.dev/reference/react", R, "Reference for React hooks and APIs."),
    ("Redux", "Redux Documentation", "https://redux.js.org/introduction/getting-started", D, "Official Redux and Redux Toolkit docs."),
    ("Next.js", "Next.js Documentation", "https://nextjs.org/docs", D, "Official Next.js documentation."),
    ("Angular", "Angular Documentation", "https://angular.dev/overview", D, "Official Angular documentation."),
    ("Vue.js", "Vue.js Guide", "https://vuejs.org/guide/introduction.html", D, "Official Vue.js guide."),
    ("Responsive Design", "MDN Responsive Design", "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design", G, "Building layouts that adapt to any screen."),
    ("Accessibility", "MDN Accessibility", "https://developer.mozilla.org/en-US/docs/Web/Accessibility", D, "Web accessibility guides and references."),
    ("Accessibility", "W3C WAI Fundamentals", "https://www.w3.org/WAI/fundamentals/", G, "Introduction to web accessibility from the W3C."),
    ("Sass", "Sass Documentation", "https://sass-lang.com/documentation/", D, "Official Sass documentation."),
    ("Bootstrap", "Bootstrap Documentation", "https://getbootstrap.com/docs/", D, "Official Bootstrap documentation."),
    ("Webpack", "Webpack Concepts", "https://webpack.js.org/concepts/", D, "Official webpack documentation."),
    ("Vite", "Vite Guide", "https://vite.dev/guide/", D, "Official Vite documentation."),
    ("Node.js", "Node.js Learn", "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs", T, "Official introduction to Node.js."),
    ("Node.js", "Node.js API Documentation", "https://nodejs.org/docs/latest/api/", R, "Node.js runtime API reference."),
    ("Express.js", "Express Documentation", "https://expressjs.com/en/starter/installing.html", D, "Official Express.js guide."),
    ("Flask", "Flask Documentation", "https://flask.palletsprojects.com/", D, "Official Flask documentation and tutorial."),
    ("Django", "Django Documentation", "https://docs.djangoproject.com/en/stable/", D, "Official Django documentation."),
    ("FastAPI", "FastAPI Documentation", "https://fastapi.tiangolo.com/", D, "Official FastAPI documentation."),
    ("Spring Boot", "Spring Boot Reference", "https://docs.spring.io/spring-boot/index.html", D, "Official Spring Boot documentation."),
    ("Spring Boot", "Spring Guides", "https://spring.io/guides", T, "Official task-focused Spring guides."),
    ("Hibernate", "Hibernate ORM Documentation", "https://hibernate.org/orm/documentation/", D, "Official Hibernate ORM docs."),
    (".NET", ".NET Documentation", "https://learn.microsoft.com/en-us/dotnet/", D, "Official Microsoft .NET documentation."),
    ("C#", "C# Documentation", "https://learn.microsoft.com/en-us/dotnet/csharp/", D, "Official C# language documentation."),
    ("C++", "cppreference.com", "https://en.cppreference.com/", R, "Comprehensive C++ language and library reference."),
    ("Go", "Go Documentation", "https://go.dev/doc/", D, "Official Go documentation."),
    ("Go", "A Tour of Go", "https://go.dev/tour/", T, "Interactive introduction to Go."),
    ("Rust", "The Rust Programming Language", "https://doc.rust-lang.org/book/", G, "The official Rust book."),
    ("PHP", "PHP Manual", "https://www.php.net/manual/en/", D, "Official PHP manual."),
    ("Kotlin", "Kotlin Documentation", "https://kotlinlang.org/docs/home.html", D, "Official Kotlin documentation."),
    ("Scala", "Scala Documentation", "https://docs.scala-lang.org/", D, "Official Scala documentation."),
    ("R", "R for Data Science", "https://r4ds.hadley.nz/", G, "Free book on data science with R."),
    ("Bash", "GNU Bash Manual", "https://www.gnu.org/software/bash/manual/", D, "Official Bash reference manual."),
    ("REST APIs", "MDN HTTP Documentation", "https://developer.mozilla.org/en-US/docs/Web/HTTP", D, "HTTP methods, status codes and headers used by REST APIs."),
    ("GraphQL", "Learn GraphQL", "https://graphql.org/learn/", D, "Official GraphQL introduction."),
    ("gRPC", "gRPC Documentation", "https://grpc.io/docs/", D, "Official gRPC documentation."),
    ("Microservices", "Microservices.io Patterns", "https://microservices.io/patterns/", R, "Catalogue of microservice architecture patterns."),
    ("SQL", "MySQL Tutorial (Reference Manual)", "https://dev.mysql.com/doc/refman/8.0/en/tutorial.html", T, "Official introduction to writing SQL queries."),
    ("SQL", "PostgreSQL: The SQL Language", "https://www.postgresql.org/docs/current/sql.html", D, "SQL language chapter of the PostgreSQL manual."),
    ("MySQL", "MySQL Documentation", "https://dev.mysql.com/doc/", D, "Official MySQL documentation."),
    ("PostgreSQL", "PostgreSQL Documentation", "https://www.postgresql.org/docs/", D, "Official PostgreSQL documentation."),
    ("SQL Server", "SQL Server Documentation", "https://learn.microsoft.com/en-us/sql/sql-server/", D, "Official Microsoft SQL Server docs."),
    ("MongoDB", "MongoDB Documentation", "https://www.mongodb.com/docs/", D, "Official MongoDB documentation."),
    ("Redis", "Redis Documentation", "https://redis.io/docs/latest/", D, "Official Redis documentation."),
    ("Elasticsearch", "Elastic Documentation", "https://www.elastic.co/guide/index.html", D, "Official Elasticsearch documentation."),
    ("Firebase", "Firebase Documentation", "https://firebase.google.com/docs", D, "Official Firebase documentation."),
    ("Git", "Git Documentation", "https://git-scm.com/doc", D, "Official Git documentation."),
    ("Git", "Pro Git Book", "https://git-scm.com/book/en/v2", G, "The free, official Pro Git book."),
    ("GitHub", "GitHub Docs", "https://docs.github.com/en", D, "Official GitHub documentation."),
    ("CI/CD", "GitHub Actions Documentation", "https://docs.github.com/en/actions", D, "Build CI/CD pipelines with GitHub Actions."),
    ("Jenkins", "Jenkins User Documentation", "https://www.jenkins.io/doc/", D, "Official Jenkins documentation."),
    ("Docker", "Docker Documentation", "https://docs.docker.com/", D, "Official Docker documentation."),
    ("Docker", "Docker Get Started", "https://docs.docker.com/get-started/", T, "Official Docker getting-started guide."),
    ("Kubernetes", "Kubernetes Documentation", "https://kubernetes.io/docs/home/", D, "Official Kubernetes documentation."),
    ("Kubernetes", "Kubernetes Tutorials", "https://kubernetes.io/docs/tutorials/", T, "Official Kubernetes tutorials."),
    ("Terraform", "Terraform Documentation", "https://developer.hashicorp.com/terraform/docs", D, "Official Terraform documentation."),
    ("Terraform", "Terraform Tutorials", "https://developer.hashicorp.com/terraform/tutorials", T, "Official HashiCorp tutorials."),
    ("Ansible", "Ansible Documentation", "https://docs.ansible.com/", D, "Official Ansible documentation."),
    ("Linux", "Ubuntu: The Linux Command Line for Beginners", "https://ubuntu.com/tutorials/command-line-for-beginners", T, "Hands-on introduction to the Linux shell."),
    ("Linux", "The Linux Documentation Project", "https://tldp.org/", R, "Guides and HOWTOs for Linux."),
    ("Nginx", "NGINX Documentation", "https://nginx.org/en/docs/", D, "Official NGINX documentation."),
    ("Monitoring", "Prometheus Documentation", "https://prometheus.io/docs/introduction/overview/", D, "Official Prometheus documentation."),
    ("Monitoring", "Grafana Documentation", "https://grafana.com/docs/grafana/latest/", D, "Official Grafana documentation."),
    ("Networking", "Cloudflare Learning Center", "https://www.cloudflare.com/learning/", G, "Clear explanations of networking and internet concepts."),
    ("AWS", "AWS Documentation", "https://docs.aws.amazon.com/", D, "Official Amazon Web Services documentation."),
    ("Azure", "Azure Documentation", "https://learn.microsoft.com/en-us/azure/", D, "Official Microsoft Azure documentation."),
    ("Google Cloud", "Google Cloud Documentation", "https://cloud.google.com/docs", D, "Official Google Cloud documentation."),
    ("IAM", "OWASP Authentication Cheat Sheet", "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html", R, "Best practices for authentication and identity."),
    ("Data Analysis", "pandas Getting Started", "https://pandas.pydata.org/docs/getting_started/index.html", T, "Official introduction to data analysis with pandas."),
    ("Pandas", "pandas Documentation", "https://pandas.pydata.org/docs/", D, "Official pandas documentation."),
    ("NumPy", "NumPy Documentation", "https://numpy.org/doc/stable/", D, "Official NumPy documentation."),
    ("Matplotlib", "Matplotlib Documentation", "https://matplotlib.org/stable/index.html", D, "Official Matplotlib documentation."),
    ("Data Visualization", "Matplotlib Tutorials", "https://matplotlib.org/stable/tutorials/index.html", T, "Official plotting tutorials."),
    ("Excel", "Microsoft Excel Help & Learning", "https://support.microsoft.com/en-us/excel", D, "Official Excel training and help."),
    ("Power BI", "Power BI Documentation", "https://learn.microsoft.com/en-us/power-bi/", D, "Official Microsoft Power BI documentation."),
    ("Tableau", "Tableau Free Training", "https://www.tableau.com/learn/training", C, "Official Tableau training videos."),
    ("Statistics", "OpenIntro Statistics", "https://www.openintro.org/book/os/", G, "Free, open-source introductory statistics textbook."),
    ("Statistics", "Khan Academy Statistics & Probability", "https://www.khanacademy.org/math/statistics-probability", C, "Free statistics course."),
    ("ETL", "Apache Airflow Documentation", "https://airflow.apache.org/docs/", D, "Orchestrate data pipelines with Airflow."),
    ("Apache Airflow", "Apache Airflow Documentation", "https://airflow.apache.org/docs/", D, "Official Apache Airflow documentation."),
    ("Apache Spark", "Apache Spark Documentation", "https://spark.apache.org/docs/latest/", D, "Official Apache Spark documentation."),
    ("Hadoop", "Apache Hadoop Documentation", "https://hadoop.apache.org/docs/stable/", D, "Official Apache Hadoop documentation."),
    ("Machine Learning", "scikit-learn User Guide", "https://scikit-learn.org/stable/user_guide.html", D, "Machine learning concepts and algorithms with scikit-learn."),
    ("Machine Learning", "Google Machine Learning Crash Course", "https://developers.google.com/machine-learning/crash-course", C, "Free introductory ML course from Google."),
    ("scikit-learn", "scikit-learn Documentation", "https://scikit-learn.org/stable/", D, "Official scikit-learn documentation."),
    ("Feature Engineering", "scikit-learn: Preprocessing Data", "https://scikit-learn.org/stable/modules/preprocessing.html", D, "Scaling, encoding and transforming features."),
    ("Deep Learning", "Dive into Deep Learning", "https://d2l.ai/", G, "Free interactive deep learning book."),
    ("Deep Learning", "Deep Learning (Goodfellow et al.)", "https://www.deeplearningbook.org/", R, "Standard deep learning textbook, free online."),
    ("TensorFlow", "TensorFlow Learn", "https://www.tensorflow.org/learn", D, "Official TensorFlow documentation."),
    ("TensorFlow", "TensorFlow Tutorials", "https://www.tensorflow.org/tutorials", T, "Official TensorFlow tutorials."),
    ("PyTorch", "PyTorch Documentation", "https://pytorch.org/docs/stable/index.html", D, "Official PyTorch documentation."),
    ("PyTorch", "PyTorch Tutorials", "https://pytorch.org/tutorials/", T, "Official PyTorch tutorials."),
    ("NLP", "Advanced NLP with spaCy (free course)", "https://course.spacy.io/", C, "Free interactive NLP course from the spaCy team."),
    ("NLP", "Hugging Face LLM & NLP Course", "https://huggingface.co/learn/nlp-course", C, "Free course on modern NLP."),
    ("spaCy", "spaCy Usage Documentation", "https://spacy.io/usage", D, "Official spaCy documentation."),
    ("NLTK", "NLTK Book", "https://www.nltk.org/book/", G, "Natural Language Processing with Python (free)."),
    ("Hugging Face", "Transformers Documentation", "https://huggingface.co/docs/transformers/index", D, "Official Hugging Face Transformers docs."),
    ("MLOps", "MLflow Documentation", "https://mlflow.org/docs/latest/index.html", D, "Track, package and deploy ML models."),
    ("Computer Vision", "OpenCV Documentation", "https://docs.opencv.org/4.x/", D, "Official OpenCV documentation."),
    ("Jupyter", "Jupyter Documentation", "https://docs.jupyter.org/en/latest/", D, "Official Project Jupyter documentation."),
    ("Software Testing", "The Practical Test Pyramid", "https://martinfowler.com/articles/practical-test-pyramid.html", G, "Structuring a balanced test suite."),
    ("Unit Testing", "Unit Test (Martin Fowler)", "https://martinfowler.com/bliki/UnitTest.html", R, "What unit tests are and how to write them."),
    ("Test Automation", "Selenium Documentation", "https://www.selenium.dev/documentation/", D, "Browser automation with Selenium."),
    ("Selenium", "Selenium Documentation", "https://www.selenium.dev/documentation/", D, "Official Selenium WebDriver documentation."),
    ("Cypress", "Cypress Documentation", "https://docs.cypress.io/", D, "Official Cypress documentation."),
    ("Playwright", "Playwright Documentation", "https://playwright.dev/docs/intro", D, "Official Playwright documentation."),
    ("JUnit", "JUnit User Guide", "https://junit.org/junit5/docs/current/user-guide/", D, "Official JUnit 5 user guide."),
    ("pytest", "pytest Documentation", "https://docs.pytest.org/", D, "Official pytest documentation."),
    ("Jest", "Jest Getting Started", "https://jestjs.io/docs/getting-started", D, "Official Jest documentation."),
    ("API Testing", "Postman Learning Center", "https://learning.postman.com/docs/introduction/overview/", D, "Design and test APIs with Postman."),
    ("Postman", "Postman Learning Center", "https://learning.postman.com/docs/introduction/overview/", D, "Official Postman documentation."),
    ("Performance Testing", "Apache JMeter User Manual", "https://jmeter.apache.org/usermanual/index.html", D, "Official JMeter documentation."),
    ("Cucumber", "Cucumber Documentation", "https://cucumber.io/docs/", D, "Official Cucumber / BDD documentation."),
    ("Agile", "The Scrum Guide", "https://scrumguides.org/scrum-guide.html", G, "The official definition of Scrum."),
    ("Agile", "Manifesto for Agile Software Development", "https://agilemanifesto.org/", R, "The values and principles of Agile."),
    ("Jira", "Jira Cloud Documentation", "https://support.atlassian.com/jira-software-cloud/", D, "Official Jira documentation."),
    ("Cybersecurity", "NIST Cybersecurity Framework", "https://www.nist.gov/cyberframework", R, "Framework for managing cybersecurity risk."),
    ("Cybersecurity", "OWASP Foundation", "https://owasp.org/", R, "Open resources for application security."),
    ("Vulnerability Assessment", "OWASP Top Ten", "https://owasp.org/www-project-top-ten/", R, "The most critical web application security risks."),
    ("Penetration Testing", "OWASP Web Security Testing Guide", "https://owasp.org/www-project-web-security-testing-guide/", G, "Comprehensive web security testing methodology."),
    ("SIEM", "Splunk Documentation", "https://docs.splunk.com/Documentation", D, "Official Splunk documentation."),
    ("Incident Response", "NIST SP 800-61 Incident Handling Guide", "https://csrc.nist.gov/pubs/sp/800/61/r2/final", G, "NIST computer security incident handling guide."),
    ("Firewalls", "What is a firewall? (Cloudflare)", "https://www.cloudflare.com/learning/security/what-is-a-firewall/", G, "How firewalls work."),
    ("Wireshark", "Wireshark Documentation", "https://www.wireshark.org/docs/", D, "Official Wireshark documentation."),
    ("Cryptography", "What is encryption? (Cloudflare)", "https://www.cloudflare.com/learning/ssl/what-is-encryption/", G, "Introduction to encryption and TLS."),
    ("Data Structures", "Open Data Structures", "https://opendatastructures.org/", G, "Free textbook on data structures."),
    ("Algorithms", "MIT 6.006 Introduction to Algorithms", "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", C, "Free MIT OpenCourseWare algorithms course."),
    ("OOP", "Java Tutorials: OOP Concepts", "https://docs.oracle.com/javase/tutorial/java/concepts/index.html", T, "Object-oriented programming concepts."),
    ("OOP", "Python Tutorial: Classes", "https://docs.python.org/3/tutorial/classes.html", T, "Classes and objects in Python."),
    ("System Design", "The System Design Primer", "https://github.com/donnemartin/system-design-primer", G, "Widely used open guide to designing large-scale systems."),
    ("Android", "Android Developers Documentation", "https://developer.android.com/docs", D, "Official Android developer documentation."),
    ("Android", "Android Developers Courses", "https://developer.android.com/courses", C, "Official free Android courses."),
    ("iOS", "Apple Developer Documentation", "https://developer.apple.com/documentation/", D, "Official Apple platform documentation."),
    ("Swift", "The Swift Programming Language", "https://docs.swift.org/swift-book/", G, "The official Swift book."),
    ("Flutter", "Flutter Documentation", "https://docs.flutter.dev/", D, "Official Flutter documentation."),
    ("Dart", "Dart Documentation", "https://dart.dev/guides", D, "Official Dart documentation."),
    ("React Native", "React Native Documentation", "https://reactnative.dev/docs/getting-started", D, "Official React Native documentation."),
]
